Repository FireWork-Production-Private-Ltd/post-types-order-by-firework, pull requests merged in 2024-06, with the labels that each got.

#6 Feature/plugin post types order
  .github/workflows/phpcs.yml
  .gitignore
  composer.json
  phpcs.xml
  plugins/post-types-order/compatibility/class-pto-compatibility-formidables.php
  plugins/post-types-order/compatibility/class-pto-events-calendar.php
  plugins/post-types-order/compatibility/class-pto-litespeed-cache.php
  plugins/post-types-order/compatibility/themes/class-pto-enfold.php
  plugins/post-types-order/composer.json
  plugins/post-types-order/composer.phar
  plugins/post-types-order/css/cpt-archive-dd.css
  plugins/post-types-order/css/cpt-options.css
  plugins/post-types-order/css/cpt.css
  plugins/post-types-order/images/menu-icon.png
  plugins/post-types-order/include/class-cpt-compatibility.php
  plugins/post-types-order/include/class-cpto.php
  plugins/post-types-order/include/class-cptofunctions.php
  plugins/post-types-order/include/class-cptooptionsinterface.php
  plugins/post-types-order/include/class-post-types-order-walker.php
  plugins/post-types-order/js/cpt.js
  plugins/post-types-order/languages/post-types-order.mo
  plugins/post-types-order/languages/post-types-order.po
  plugins/post-types-order/post-types-order.php
  plugins/post-types-order/readme.txt
  plugins/post-types-order/screenshot-1.png
  plugins/post-types-order/screenshot-2.png
  themes/.gitkeep
Labels: enhancement, plugin

#8 update: readme text and version
  .gitignore
  composer.json
  plugins/post-types-order-by-firework.zip
  plugins/post-types-order-by-firework/compatibility/class-pto-compatibility-formidables.php
  plugins/post-types-order-by-firework/compatibility/class-pto-events-calendar.php
  plugins/post-types-order-by-firework/compatibility/class-pto-litespeed-cache.php
  plugins/post-types-order-by-firework/composer.json
  plugins/post-types-order-by-firework/css/cpt-archive-dd.css
  plugins/post-types-order-by-firework/css/cpt-options.css
  plugins/post-types-order-by-firework/css/cpt.css
  plugins/post-types-order-by-firework/images/menu-icon.png
  plugins/post-types-order-by-firework/include/class-cpt-compatibility.php
  plugins/post-types-order-by-firework/include/class-cpto.php
  plugins/post-types-order-by-firework/include/class-cptofunctions.php
  plugins/post-types-order-by-firework/include/class-cptooptionsinterface.php
  plugins/post-types-order-by-firework/include/class-post-types-order-walker.php
  plugins/post-types-order-by-firework/js/cpt.js
  plugins/post-types-order-by-firework/languages/.gitkeep
  plugins/post-types-order-by-firework/post-types-order-by-firework.php
  plugins/post-types-order-by-firework/readme.md
  plugins/post-types-order-by-firework/readme.txt
  plugins/post-types-order-by-firework/screenshot-1.png
  plugins/post-types-order-by-firework/screenshot-2.png
  plugins/post-types-order/compatibility/class-pto-events-calendar.php
  plugins/post-types-order/composer.phar
  plugins/post-types-order/languages/post-types-order.mo
  plugins/post-types-order/languages/post-types-order.po
  plugins/post-types-order/readme.txt
Labels: enhancement, plugin

#9 feature: directory readme
  readme.md
Labels: enhancement, plugin

#10 fix: image issues
  readme.md
Labels: enhancement

#15 Update readme.md
  readme.md
Labels: failed workflow
